name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Check code styling
      run: dotnet format --verify-no-changes

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [6.0.x]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore Tests/Tests.csproj
    - name: Build
      run: dotnet build Tests/Tests.csproj --no-restore
    - name: Test
      run: dotnet test Tests/Tests.csproj --no-build --verbosity normal
